version: "3.9"
services:
  postgres:
    container_name: postgres
    image: fds-postgres
    build: ./db/postgres/.
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - APP_DB_USER=api
      - APP_DB_PASS=1234
      - APP_DB_NAME=main
    ports:
      - 5432
    networks:
      - db
    # wait till all scripts are done etc.
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  redis:
    container_name: redis
    image: fds-redis
    build: ./db/redis/.
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - 6379
    networks:
      - db
  
  api:
    restart: on-failure
    container_name: fds-api
    image: fds-api
    build: ./api/.
    depends_on:
      - postgres
    environment:
      POSTGRES_URL: postgresql://api:1234@postgres:5432/main
      REDIS_ADR: redis
      REDIS_PORT: 6379
    networks:
      - db
  
    ports: 
      - 3001:8000

networks:
  db:
    name: db
  
